# variable -> dynamic value assignment
# stop nginx
# disbale nginx
#install httpd
#variablen -> dynamic value assignment

---

- name: convert lemp into lamp
  hosts: localhost
  become: yes

  # define variable and assign values

  vars:

    new_pkg: httpd

    web_pkg: nginx # hard codeing

    db_pkg: mariadb105-server

    php_pkg:

     - php

     - php-fpm

    web_service: nginx

    db_service: mariadb

    php_service: php-fpm

    new_pkg_service: httpd

    web_file_path: /var/www/html/index.php

  tasks:

  - name: install httpd

    ansible.builtin.dnf:

     name: "{{new_pkg}}"

     state: present

  - name: install nginx

    ansible.builtin.dnf:

      name: "{{web_pkg}}" # varaible call

      state: present

  - name: install mariadb

    ansible.builtin.dnf:

      name: "{{db_pkg}}"

      state: present

  - name: install php-fpm

    ansible.builtin.dnf:

      name: "{{php_pkg}}"

      state: present

  - name: stop and disable nginx

    ansible.builtin.systemd_service:

      name: "{{web_service}}"

      state: stopped

      enabled: false

  - name: start and enable httpd

    ansible.builtin.systemd_service:

      name: "{{new_pkg_service}}"

      state: started

      enabled: true

  - name: start and enable mariadb

    ansible.builtin.systemd_service:

      name: "{{db_service}}"

      state: started

      enabled: true

  - name: start and enable php-fpm

    ansible.builtin.systemd_service:

      name: "{{php_service}}"

      state: started

      enabled: true

  - name : deploy php page

    ansible.builtin.copy:

      dest: "{{web_file_path}}"

      content: |

        <?php

        phpinfo();

        ?>

   


